---
version: '3.8'
services:

  beenserve-admin:
    container_name: bs-admin
    image: bs-69-admin:latest
    depends_on:
      users_db:
        condition: service_healthy
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      WEB_SERVER_PORT: "${WEB_SERVER_PORT}"

    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    restart:
      unless-stopped

  beenserve-client:
    container_name: bs-client
    image: bs-69-client:latest
    depends_on:
      tealacarte_db:
        condition: service_healthy
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      STRIPE_KEY: "${STRIPE_KEY}"
      STRIPE_PUBLISHABLE_KEY: "${STRIPE_PUBLISHABLE_KEY}"
      WEB_SERVER_PORT: "${WEB_SERVER_PORT}"
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    restart:
      unless-stopped

  user_db:
    container_name: userDb
    image: postgres:15.1
    environment:
      PGPORT: "${DATABASE_PORT}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    user: "1000:100"
    volumes:
      - ./data/${PRODUCT_DATABASE_INIT}:/docker-entrypoint-initdb.d/001_init.sql
      - ./data/user_db_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart:
      unless-stopped
    healthcheck:
      test: ["CMD-SHELL",
             "pg_isready -d ${POSTGRES_USER} -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 10s
      retries: 8

  product_db:
    container_name: productDb
    image: postgres:15.1
    environment:
      PGPORT: "${DATABASE_PORT}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./data/${PRODUCT_DATABASE_INIT}:/docker-entrypoint-initdb.d/001_init.sql
      - ./data/${PRODUCT_DATA_INJECTION}:/docker-entrypoint-initdb.d/002_data.sql
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart:
      unless-stopped
    healthcheck:
      test: ["CMD-SHELL",
             "pg_isready -d ${POSTGRES_USER} -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 10s
      retries: 8

  log_db:
    container_name: log_db
    image: postgres:15.1
    environment:
      PGPORT: "${LOG_DB_PORT}"
      POSTGRES_USER: "logdb"
      POSTGRES_PASSWORD: "test123"
    user: "1000:100"
    volumes:
      - ./data/${LOG_DB_INIT}:/docker-entrypoint-initdb.d/001_init.sql
      - ./data/log_db_data:/var/lib/postgresql/data
    ports:
      - "${LOG_DB_PORT}:${LOG_DB_PORT}"
    restart:
      unless-stopped
