---
version: '3.8'
services:
  tealacarte_db:
    container_name: tealacarte
    image: postgres:15.1
    environment:
      PGPORT: "5432"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./data/${PRODUCT_DATABASE_INIT}:/docker-entrypoint-initdb.d/001_init.sql
      - ./data/${PRODUCT_DATA_INJECTION}:/docker-entrypoint-initdb.d/002_data.sql
    ports:
      - "5432:5432"
    restart:
      unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 8

  beenserve:
    container_name: been_serve
    image: bs-69:latest
    depends_on:
      tealacarte_db:
        condition: service_healthy
    ports:
      - "9090:9090"
    restart:
      unless-stopped
