#!/usr/bin/env bash

while getopts 'cbr' OPTION; do
    case "$OPTION" in
        c)
            docker compose down
            docker rmi $(docker images -f dangling=true -q)
            ;;
        b)
            npm run build 
            docker build -f Test_Env.Dockerfile . -t bs-69-client
            docker build -f Admin_Env.Dockerfile . -t bs-69-admin
            ;;
        r)
            docker compose up -d
            ;;
        *)
            echo "Invalid flag"
            exit 1
            ;;
    esac
done
