FROM golang:1.20-rc-bullseye

#RUN apt-get -y update && apt-get -y upgrade
#RUN apt-get -y install git && rm -rf /var/cache/apk/*
#RUN git clone https://github.com/senorgato/beenserve.git && cd beenserve
#WORKDIR /beenserve
#RUN go mod download && go mod verify
#RUN go build -v -o /usr/local/bin/app ./...
#
CMD ["bash"]
#CMD ["app"]
